//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngenioTest.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IngenioTestEntities : DbContext
    {
        public IngenioTestEntities()
            : base("name=IngenioTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingenio> Ingenios { get; set; }
    
        public virtual ObjectResult<ExerciseB_Result> ExerciseB(Nullable<int> inCatlevel)
        {
            var inCatlevelParameter = inCatlevel.HasValue ?
                new ObjectParameter("inCatlevel", inCatlevel) :
                new ObjectParameter("inCatlevel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExerciseB_Result>("ExerciseB", inCatlevelParameter);
        }
    }
}
